    -keep class com.dephub.android.cardview.Cardadapter { *; }
    -keep class com.dephub.android.cardview.Cardmodel { *; }
    -keep class com.dephub.android.firebase.OfflineSync { *; }
    -keep class com.dephub.android.activity.Introduction { *; }
    -keep class com.dephub.android.firebase.Messaging { *; }
