name: Node.js CI

on:
  push:
    branches:
      - web
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Libraries    
        run: |
          cd react
          npm install --force

      - name: Build React app
        run: |
          cd react
          npm run build
        
      - name: Move React Build to Root
        run: |
          mkdir -p web/static
          cp -R react/build/static/* web/static/
          cp -R react/build/* web/
